# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

#colorScheme = "blowfish"
colorScheme = "avocado"
defaultAppearance = "dark" # valid options: light or dark
#autoSwitchAppearance = true
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

#mainSections = ["docs"]
# robots = ""

disableImageOptimization = false

#defaultBackgroundImage = "/img/ocean.jpg"
#defaultFeaturedImage = "/img/ocean.jpg"
defaultBackgroundImage = "/images/pexels-neo-html.jpeg" # used as default for background images
#defaultFeaturedImage = "/images/featured_ps.jpg" # used as default for featured images in all articles
defaultFeaturedImage = "/images/featured_p03.jpg" # used as default for featured images in all articles

highlightCurrentMenuArea = true
smartTOC = true
#smartTOCHideUnfocusedChildren = false

#[params]
#[params.author]
#    name = "zd"
#[author]
#  name = "zd"

[header]
  #layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur
  layout = "basic" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  #showThemeAttribution = true
  #showAppearanceSwitcher = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  #layout = "custom" # valid options: page, profile, hero, card, background, custom
  #layout = "profile" # valid options: page, profile, hero, card, background, custom
  layout = "background" # valid options: page, profile, hero, card, background, custom
  # homepageImage = "/img/iceland.jpg" # used in: hero, and card
  homepageImage = "/images/pexels-neo-html.jpeg" # used in: hero, and card
  #showRecent = false
  showRecent = true
  #showRecentItems = 12
  showRecentItems = 3
  showMoreLink = true
  #showMoreLinkDest = "docs"
  showMoreLinkDest = "/posts"
  #cardView = false
  cardView = true
  cardViewScreenWidth = false
  #layoutBackgroundBlur = true # only used when layout equals background
  layoutBackgroundBlur = false # only used when layout equals background

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateUpdated = false
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackgrouthumbAndBackgroundnd
  # heroStyle = "basic" # valid options: basic, big, background, thumbAndBackground
  #layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  #layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  layoutBackgroundBlur = true # only used when heroStyle equals background
  #showBreadcrumbs = true
  showBreadcrumbs = false
  showDraftLabel = true
  #showEdit = true
  showEdit = false
  #editURL = "https://github.com/nunocoracao/blowfish/tree/main/exampleSite/content"
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = false  # showPrevious, showNext
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true 
  showAuthor = true
  showAuthorsBadges = true 
  showAuthorBottom = true
  showWordCount = true
  # sharingLinks = [ "linkedin", "twitter", "reddit", "whatsapp", "telegram", "pinterest", "facebook", "email"]
  # sharingLinks = [ "linkedin", "twitter", "reddit", "pinterest", "facebook", "email", "whatsapp", "telegram"]
  sharingLinks = [ "linkedin", "twitter", "reddit", "facebook" ]


#[list]
#  showHero = true
#  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  layoutBackgroundBlur = true # only used when heroStyle equals background
#  layoutBackgroundHeaderSpace = false
#  showBreadcrumbs = false
#  showSummary = false
#  showViews = true
#  showLikes = true
#  showTableOfContents = true
#  showCards = true
#  groupByYear = false
#  cardView = true
#  cardViewScreenWidth = false
#  constrainItemsWidth = false

[list]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = ["taxonomy","term"]

#[taxonomy]
#  showTermCount = true
#  showHero = true
#  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  showBreadcrumbs = false
#  showViews = true
#  showLikes = true
#  showTableOfContents = true
#  cardView = false

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

#[term]
#  showHero = true
#  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
#  showBreadcrumbs = false
#  showViews = true
#  showLikes = true
#  showTableOfContents = true
#  groupByYear = false
#  cardView = true
#  cardViewScreenWidth = false
  
[term]
  showHero = true
  heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

[firebase]
  #apiKey = "AIzaSyB5tqlqDky77Vb4Tc4apiHV4hRZI18KGiY"
  apiKey = "AIzaSyAjMb5JN8Lt6eFYQxoun9GyzgSbFkcpluc"
  #authDomain = "blowfish-21fff.firebaseapp.com"
  authDomain = "myseq-gh-pages.firebaseapp.com"
  #projectId = "blowfish-21fff"
  projectId = "myseq-gh-pages"
  #storageBucket = "blowfish-21fff.appspot.com"
  storageBucket = "myseq-gh-pages.appspot.com"
  #messagingSenderId = "60108104191"
  messagingSenderId = "991404758454"
  #appId = "1:60108104191:web:039842ebe1370698b487ca"
  appId = "1:991404758454:web:2cde04db7ae17a22135d17"
  #measurementId = "G-PEDMYR1V0K"
  #measurementId = "G-CQL491X0G6"
  measurementId = "G-HEVCNH0EFT"

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = "myseq"
  # globalWidget = true
  # globalWidgetMessage = ""
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
   google = "G-CQL491X0G6"
  # bing = ""
  # pinterest = ""
  # yandex = ""

