name: Deploy Hugo Site

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true # Ensures submodules are fetched
          fetch-depth: 0   # Ensures full history for submodules

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          #hugo-version: 'latest'
          hugo-version: 0.139.0
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


